name: caps_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  # https://pub.dev/packages/cupertino_icons, MIT license: Copyright (c) 2016 Vladimir Kharlampidi
  
  firebase_auth: ^0.20.0+1
  # https://pub.dev/packages/firebase_auth, BSD license: Copyright 2017 The Chromium Authors
  
  cloud_firestore: ^0.16.0
  # https://pub.dev/packages/cloud_firestore, BSD license: Copyright 2017, the Chromium project authors
  
  firebase_core: ^0.7.0
  # https://pub.dev/packages/firebase_core, BSD license: Copyright 2017 The Chromium Authors
  
  provider: ^4.3.2+4
  # https://pub.dev/packages/provider, MIT license: Copyright (c) 2019 Remi Rousselet
  
  audioplayers: ^0.10.0
  # https://pub.dev/packages/audioplayers, MIT license: Copyright (c) 2017 Luan Nico
  
  uuid: ^2.2.2
  # https://pub.dev/packages/uuid, MIT license: Copyright (c) 2012 Yulian Kuncheff
  
  auto_size_text: ^2.1.0
  # https://pub.dev/packages/auto_size_text, MIT license:Copyright (c) 2018 Simon Leier
  
  fluttertoast: ^7.1.6
  # https://pub.dev/packages/fluttertoast, MIT license: Copyright (c) 2020 Karthik Ponnam
  
  keyboard_visibility: ^0.5.6
  # https://pub.dev/packages/keyboard_visibility, MIT license: Copyright (c) 2006-2018

  bidirectional_scroll_view: ^0.1.1
  #https://pub.dev/packages/bidirectional_scroll_view, BSD license: Copyright (c) toufikzitouni

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PirataOne
      fonts:
        - asset: assets/fonts/PirataOne-Regular.ttf
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Light.otf
        - asset: assets/fonts/NotoSansJP-Medium.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Thin.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
